export interface EventWrapper<T> {
  eventType: EventType;
  message: T;
}

export const EventType = {
  MOVEMENT_ADDED: "MOVEMENT_ADDED",
  MOVEMENT_DELETED: "MOVEMENT_DELETED",
  SERVICE_PAID: "SERVICE_PAID",
  SERVICE_UPDATED: "SERVICE_UPDATED",
  SERVICE_DELETED: "SERVICE_DELETED",
  INVITATION_CONFIRMED_REJECTED: "INVITATION_CONFIRMED_REJECTED",
  INVITATION_ADDED: "INVITATION_ADDED",
  MEMBERSHIP_UPDATED: "MEMBERSHIP_UPDATED",
} as const;
export type EventType = (typeof EventType)[keyof typeof EventType];
